version: "2.4"
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  editor:
    image: lblod/frontend-embeddable-editor:1.0.1
    links:
      - identifier:backend
    restart: always
    logging: *default-logging
  identifier:
    image: semtech/mu-identifier:1.8.1
    restart: always
    logging: *default-logging
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"}]"
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: '*'
  deltanotifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.1
    volumes:
      - ./config/dispatcher:/config
    restart: always
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.5
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
      DATABASE_COMPATIBILITY: Virtuoso
    volumes:
      - ./config/authorization:/config
    restart: always
    logging: *default-logging
  virtuoso:
    image: redpencil/virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/db/virtuoso.ini:/data/virtuoso.ini
    restart: always
    logging: *default-logging
  cache:
    image: semtech/mu-cache:2.0.1
    links:
      - resource:backend
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.20.0
    volumes:
      - ./config/resources:/config
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    restart: always
    logging: *default-logging
  project-scripts:
    image: semtech/mu-scripts:1.0.0
    volumes:
      - ./scripts/project:/app/scripts/
    restart: "no"
  codex-proxy:
    image: lblod/codex-reverse-proxy-service
    restart: always
    logging: *default-logging
